services: 
  strava-service:
    build: ./strava_service
    ports: 
      - 8080:8080

  peer-server-service:
    build: ./peer_service
    ports: 
      - 9000:9000

  crash-logging-service:
    build: ./crash_logging_service
    ports:
      - 3000:3000

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  lobby-service:
    build: ./multiplayer_services/lobby-service
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - redis

  game-service:
    build: ./multiplayer_services/game-service
    ports:
      - "4001:4001"
    env_file:
      - .env
    depends_on:
      - redis
